[app]
name = "My Application"
version = 2.1
description = """A comprehensive app
with multiple features
and great performance"""
features = [
  """authentication
with OAuth2""",
  """caching
Redis-based
with TTL""",
  60,
  "\nlogging system",
  """database
PostgreSQL"""
]

[app.settings]
host = "localhost"
port = 8080
debug = true

[app.metadata]
authors = [
  """John Doe
john@example.com""",
  "Jane Smith"
]
tags = [
  "web",
  "api",
  "",
  "production"
]
notes = """Remember to update docs
before release

Check all tests"""